export const GET_ALL_POKEMONS = 'GET_ALL_POKEMONS';
export const GET_POKEMON_BY_ID = 'GET_POKEMON_BY_ID';
export const GET_POKEMON_BY_NAME = 'GET_POKEMON_BY_NAME';
export const GET_TYPES = 'GET_TYPES';
export const CREATE_POKEMON = 'CREATE_POKEMON';

export const FILTER_BY = 'FILTER_BY';
export const SORT_BY = 'SORT_BY';

// export const FILTER_BY_TYPES = 'FILTER_BY_TYPES';
// export const FILTER_BY_CREATOR = 'FILTER_BY_CREATOR';
// export const FILTER_BY_ALPHORDER = 'FILTER_BY_ALPHORDER';
// export const FILTER_BY_ATTACK = 'FILTER_BY_ATTACK';